//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBiblioteka.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCBiblioteka.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Autorzy
        {
            get
            {
                return ResourceManager.GetString("Autorzy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Biblioteka
        {
            get
            {
                return ResourceManager.GetString("Biblioteka", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error password.
        /// </summary>
        public static string Blad_hasla
        {
            get
            {
                return ResourceManager.GetString("Blad_hasla", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Hasło
        {
            get
            {
                return ResourceManager.GetString("Hasło", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Język
        {
            get
            {
                return ResourceManager.GetString("Język", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Kategorie
        {
            get
            {
                return ResourceManager.GetString("Kategorie", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Kod
        {
            get
            {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Koszyk
        {
            get
            {
                return ResourceManager.GetString("Koszyk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Book list.
        /// </summary>
        public static string Lista_książek
        {
            get
            {
                return ResourceManager.GetString("Lista_książek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Potwierdz_haslo
        {
            get
            {
                return ResourceManager.GetString("Potwierdz_haslo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Wiadomosci
        {
            get
            {
                return ResourceManager.GetString("Wiadomosci", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Witaj
        {
            get
            {
                return ResourceManager.GetString("Witaj", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string Wydawnictwa
        {
            get
            {
                return ResourceManager.GetString("Wydawnictwa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Zaloguj
        {
            get
            {
                return ResourceManager.GetString("Zaloguj", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remeber browser?.
        /// </summary>
        public static string Zapamietac_przegladarke
        {
            get
            {
                return ResourceManager.GetString("Zapamietac_przegladarke", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remeber me !.
        /// </summary>
        public static string Zapamietaj_mnie
        {
            get
            {
                return ResourceManager.GetString("Zapamietaj_mnie", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Signin.
        /// </summary>
        public static string Zarejestruj
        {
            get
            {
                return ResourceManager.GetString("Zarejestruj", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register new account.
        /// </summary>
        public static string Zarejestruj_nowe
        {
            get
            {
                return ResourceManager.GetString("Zarejestruj_nowe", resourceCulture);
            }
        }
    }
}
